# Generated by Django 4.2.1 on 2023-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_alter_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='actiiv',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
